version: "3.7"

networks:
  backend:
    driver: bridge

services:
  ### Api ###########################################
  api:
    build:
      context: ../
      args:
        app_env: prod
    networks:
      - backend
    restart: on-failure
    ports:
      - "1323:1323"